categories:
  Teaching:
    Syllabi:
      any:
        - "\\bsyllabus\\b"
        - "course description"
        - "attendance policy"
        - "learning outcome(s?)"
        - "grading scale"
        - "late policy"
        - "academic integrity"
        - "prerequisite"
        - "course objectives"
        - "grading criteria"
        - "class schedule"
        - "required materials"
        - "accommodations policy"
    
    Assignments & Rubrics:
      any:
        - "\\bassignment\\b"
        - "\\brubric\\b"
        - "points possible"
        - "submission instructions"
        - "grading rubric"
        - "assessment criteria"
        - "performance standards"
        - "learning assessment"
        - "evaluation form"
        - "scoring guide"
        - "feedback form"
    
    Assessment/Evals:
      any:
        - "student evaluation of teaching"
        - "\\bSET\\b"
        - "IDEA survey"
        - "course evaluation"
        - "teaching evaluation"
        - "Brightspace|D2L|Canvas export"
        - "gradebook export"
        - "final grades"
        - "midterm feedback"
        - "student feedback"
        - "teaching assessment"
        - "instructor rating"
    
    Lesson Plans & Materials:
      any:
        - "\\blesson plan\\b"
        - "\\blecture\\b"
        - "\\bslides?\\b"
        - "\\bquiz\\b"
        - "\\banswer key\\b"
        - "rehearsal plan"
        - "warm-up routine"
        - "sectional plan"
        - "practice schedule"
        - "repertoire list"
        - "music selection"
        - "sight reading"
        - "scale studies"
        - "technique exercises"
        - "fundamentals"
        - "ensemble literature"
        - "concert program"
        - "recital program"
    
    Music Education Specific:
      any:
        - "music theory"
        - "music history"
        - "conducting technique"
        - "score study"
        - "ensemble technique"
        - "instrument pedagogy"
        - "music appreciation"
        - "aural skills"
        - "sight singing"
        - "keyboard skills"
        - "music technology"
        - "composition"
        - "arranging"
        - "jazz studies"
        - "world music"
        - "music therapy"
    
    Band Program Teaching:
      any:
        - "marching band"
        - "concert band"
        - "wind ensemble"
        - "jazz band"
        - "pep band"
        - "basketball band"
        - "athletic bands"
        - "wind symphony"
        - "brass ensemble"
        - "woodwind ensemble"
        - "percussion ensemble"
        - "chamber music"
        - "brass quintet"
        - "woodwind quintet"
        - "saxophone quartet"
        - "flute choir"
        - "clarinet choir"
        - "brass choir"
    
    Advising/Recruitment:
      any:
        - "\\badvis(ing|or)\\b"
        - "recruitment"
        - "audition"
        - "marching band registration"
        - "music scholarship"
        - "prospective student"
        - "high school visit"
        - "music camp"
        - "masterclass"
        - "clinic"
        - "honor band"
        - "all-state"
        - "festival"
        - "competition"
        - "adjudication"
        - "student mentoring"
        - "career guidance"
        - "graduate school prep"
        - "teacher placement"

  Service:
    Committees:
      any:
        - "\\bcommittee\\b"
        - "agenda"
        - "minutes"
        - "motion carried"
        - "meeting invite"
        - "Zoom link"
        - "faculty senate"
        - "curriculum committee"
        - "search committee"
        - "tenure committee"
        - "promotion committee"
        - "assessment committee"
        - "budget committee"
        - "safety committee"
        - "student affairs"
        - "academic standards"
        - "admissions committee"
        - "scholarship committee"
        - "diversity committee"
        - "strategic planning"
        - "accreditation"
        - "NASM"
        - "program review"
    
    Music Department Service:
      any:
        - "ensemble coordination"
        - "concert coordination"
        - "music library"
        - "instrument maintenance"
        - "instrument inventory"
        - "equipment management"
        - "rehearsal scheduling"
        - "venue coordination"
        - "music purchase"
        - "copyright clearance"
        - "performance rights"
        - "ASCAP"
        - "BMI"
        - "music licensing"
        - "recording permissions"
        - "livestream setup"
        - "sound engineering"
        - "audio recording"
        - "video production"
    
    Administrative Service:
      any:
        - "assessment report"
        - "program review"
        - "budget request"
        - "scheduling"
        - "inventory"
        - "course scheduling"
        - "room assignment"
        - "facility management"
        - "budget planning"
        - "financial report"
        - "expenditure tracking"
        - "purchase order"
        - "vendor coordination"
        - "travel arrangements"
        - "transportation"
        - "hotel reservations"
        - "meal planning"
        - "uniform management"
        - "costume coordination"
        - "instrument rental"
        - "equipment lease"
        - "insurance forms"
        - "liability waivers"
        - "medical forms"
        - "emergency contacts"
    
    Events & Outreach:
      any:
        - "parents' weekend"
        - "\\balumni\\b"
        - "\\bopen house\\b"
        - "community outreach"
        - "hosting"
        - "judging"
        - "homecoming"
        - "commencement"
        - "graduation ceremony"
        - "pep rally"
        - "football game"
        - "basketball game"
        - "athletic event"
        - "parade"
        - "festival performance"
        - "community concert"
        - "school visit"
        - "clinic presentation"
        - "masterclass hosting"
        - "guest artist"
        - "resident artist"
        - "fundraising"
        - "donor relations"
        - "sponsor coordination"
        - "media relations"
        - "press release"
        - "social media"
        - "program notes"
        - "concert program"
        - "marketing materials"
    
    Professional Service:
      any:
        - "peer review"
        - "manuscript review"
        - "journal review"
        - "conference review"
        - "grant review"
        - "tenure review"
        - "promotion review"
        - "external review"
        - "accreditation visit"
        - "site visit"
        - "consultant"
        - "advisory board"
        - "editorial board"
        - "professional organization"
        - "CBDNA"
        - "NBA"
        - "NAfME"
        - "CMS"
        - "TMEA"
        - "state music"
        - "music educators"
        - "band directors"
        - "conducting symposium"
        - "music conference"
        - "workshop presenter"
        - "clinician"
        - "adjudicator"
        - "festival judge"
        - "competition judge"

  Scholarship:
    Publications:
      any:
        - "\\bdoi:\\s*10\\."
        - "\\bISSN\\b"
        - "manuscript submitted"
        - "\\breferences\\b"
        - "accepted for publication"
        - "peer reviewed"
        - "journal article"
        - "book chapter"
        - "monograph"
        - "encyclopedia entry"
        - "review article"
        - "editorial"
        - "opinion piece"
        - "research paper"
        - "scholarly article"
        - "academic publication"
        - "music education"
        - "band literature"
        - "conducting pedagogy"
        - "music theory"
        - "music history"
        - "performance practice"
        - "wind band"
        - "brass band"
        - "community band"
        - "school band"
        - "marching band history"
        - "instrument pedagogy"
    
    Presentations:
      any:
        - "\\bconference\\b"
        - "\\babstract\\b"
        - "\\bprogram\\b"
        - "\\bposter\\b"
        - "\\bproceedings\\b"
        - "accepted to present"
        - "keynote"
        - "plenary session"
        - "panel discussion"
        - "roundtable"
        - "workshop"
        - "masterclass"
        - "clinic"
        - "demonstration"
        - "lecture recital"
        - "research presentation"
        - "CBDNA conference"
        - "NAfME conference"
        - "state music conference"
        - "regional conference"
        - "national conference"
        - "international conference"
        - "symposium"
        - "summit"
        - "colloquium"
        - "seminar"
        - "webinar"
        - "online presentation"
        - "virtual conference"
    
    Creative Works:
      any:
        - "composition"
        - "arrangement"
        - "transcription"
        - "orchestration"
        - "original work"
        - "commissioned work"
        - "premiere"
        - "world premiere"
        - "regional premiere"
        - "first performance"
        - "musical score"
        - "sheet music"
        - "published music"
        - "music publisher"
        - "copyright"
        - "performance rights"
        - "recording"
        - "album"
        - "CD"
        - "digital release"
        - "streaming"
        - "music video"
        - "documentary"
        - "educational video"
        - "instructional materials"
        - "method book"
        - "etude book"
        - "study guide"
        - "curriculum guide"
        - "drill design"
        - "show design"
        - "halftime show"
        - "field show"
        - "parade arrangement"
        - "pep tune"
        - "fight song"
        - "school song"
        - "alma mater"
        - "ceremonial music"
    
    Performances:
      any:
        - "guest conductor"
        - "guest artist"
        - "solo performance"
        - "chamber performance"
        - "orchestra performance"
        - "band performance"
        - "recital"
        - "concert"
        - "festival performance"
        - "competition performance"
        - "masterclass performance"
        - "clinic performance"
        - "demonstration performance"
        - "recording session"
        - "studio recording"
        - "live recording"
        - "broadcast performance"
        - "radio performance"
        - "television performance"
        - "streaming performance"
        - "virtual performance"
        - "outdoor concert"
        - "indoor concert"
        - "formal concert"
        - "informal performance"
        - "community performance"
        - "professional performance"
        - "amateur performance"
        - "student performance"
        - "faculty performance"
        - "collaborative performance"
        - "interdisciplinary performance"
    
    Grants/IRB:
      any:
        - "\\bIRB\\b"
        - "\\bprotocol\\b"
        - "\\bgrant\\b"
        - "budget justification"
        - "scope of work"
        - "research proposal"
        - "funding application"
        - "fellowship application"
        - "sabbatical application"
        - "travel grant"
        - "research grant"
        - "equipment grant"
        - "program grant"
        - "teaching grant"
        - "innovation grant"
        - "technology grant"
        - "diversity grant"
        - "student support grant"
        - "faculty development"
        - "professional development"
        - "conference funding"
        - "research funding"
        - "equipment funding"
        - "program funding"
        - "institutional funding"
        - "external funding"
        - "federal funding"
        - "state funding"
        - "private funding"
        - "foundation grant"
        - "corporate sponsorship"
        - "endowment funding"
        - "scholarship funding"
        - "award letter"
        - "grant notification"
        - "funding confirmation"
    
    Research Activities:
      any:
        - "research design"
        - "methodology"
        - "data collection"
        - "data analysis"
        - "statistical analysis"
        - "qualitative research"
        - "quantitative research"
        - "mixed methods"
        - "survey research"
        - "interview research"
        - "ethnographic research"
        - "case study"
        - "action research"
        - "experimental design"
        - "control group"
        - "treatment group"
        - "research ethics"
        - "informed consent"
        - "participant recruitment"
        - "research protocol"
        - "literature review"
        - "theoretical framework"
        - "research question"
        - "hypothesis"
        - "research objective"
        - "research aim"
        - "research scope"
        - "research timeline"
        - "research budget"
        - "research team"
        - "research collaboration"
        - "research partnership"
        - "research network"

file_filters:
  include_extensions:
    - ".pdf"
    - ".docx"
    - ".pptx"
    - ".txt"
    - ".doc"
    - ".rtf"
    - ".odt"
    - ".pages"
    - ".key"
    - ".odp"
    - ".xlsx"
    - ".xls"
    - ".csv"
    - ".ods"
    - ".numbers"
    - ".md"
    - ".tex"
    - ".html"
    - ".htm"
    - ".xml"
  exclude_dirs:
    - ".git"
    - "node_modules"
    - "__pycache__"
    - ".venv"
    - ".DS_Store"
    - "Thumbs.db"
    - "temp"
    - "tmp"
    - "cache"
    - "backup"
    - "archive"
    - "old"
    - "deleted"
    - "trash"

scoring:
  per_hit_points: 1
  cap_per_file: 15
  category_weights:
    Teaching: 1.0
    Service: 1.0
    Scholarship: 1.2
  bonus_keywords:
    - "NASM": 3
    - "accreditation": 3
    - "tenure": 5
    - "promotion": 5
    - "peer review": 3
    - "published": 4
    - "conference presentation": 4
    - "grant award": 5
    - "fellowship": 4
    - "sabbatical": 4
    - "CBDNA": 3
    - "NAfME": 3
    - "original composition": 5
    - "commissioned work": 5
    - "world premiere": 4
    - "guest conductor": 3
    - "masterclass": 3
    - "clinic": 2
    - "adjudicator": 2
    - "festival judge": 2
    - "honor band": 3
    - "all-state": 3
    - "national conference": 4
    - "international conference": 5
    - "keynote": 5
    - "plenary": 4
    - "editorial board": 4
    - "manuscript review": 3
    - "external review": 4
    - "consultant": 3
    - "advisory board": 3